language: rust
rust:
  - 1.45.2  # pinned toolchain for clippy
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - CLIPPY_RUST_VERSION=1.45.2

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy-preview;
    fi'

script:
  - cargo test
  - cargo test --no-default-features --features native-tokio
  - cargo test --no-default-features --features webpki-tokio
  - cargo test --no-default-features
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
